version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
